[package]
name = "renplex"
version = "0.0.1"
edition = "2021"
authors = ["Pedro Alves <pedromfa98@gmail.com>"]
description = "A library capable of handling complexed valued neural network alternatives built with Rust."
readme = "README.md"
repository = "https://github.com/Pxdr0-A/renplex"
license = "MIT"
license-file = "LICENSE"
keywords = ["neural-network-engine", "complexed-valued-neural-networks"]
categories = ["Library"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
